### ISSUE TITLE
9.2.5 breaks right click

### ISSUE THREAD

**Issue by BradCOnGitHub** [dev7355608/BlizzardRaidFramesFix#4]
If you try to right click on a raid frame it generates a lua error in 9.2.5

**Comment by SweepyBoop** [comment]
Same issue, happens every time

**Comment by SweepyBoop** [comment]
I created a fix in #5 , waiting for the owner to review and approve.

**Comment by dev7355608** [comment]
Fixed by #5. Thanks @SweepyBoop!
